### ISSUE TITLE
Failed to compile & GetText error

### ISSUE THREAD

**Issue by Palliridium** [bruno105/AltarHelper#3]
Hello,
I'm facing an issue with the latest version released earlier today. 
It seems that:

- from the .dll, I have the following issue (fresh folder, latest poehud version)

`2022-06-25 00:06:26.618 +02:00 [ERR] AltarHelper, Render -> System.MissingMethodException: Méthode introuvable : 'System.String ExileCore.PoEMemory.Element.GetText(Int32)'.
   à AltarHelper.AltarHelperCore.Render()
   à ExileCore.Shared.PluginWrapper.Render() dans /buddy/exileapi/Core/Shared/PluginWrapper.cs:ligne 208
`

- if I try to compile myself, I have the following issue as well:

`error CS1061: 'Element' does not contain a definition for 'GetText' and no accessible 'GetText' extension method accepting a first argument of type 'Element' was found (is a using directive or an assembly reference missing?)`

I'm not good enough in C# to debug this myself, any clue? Am I missing something? thx! 
@bruno105 

A huge thank you for your appreciated work!

**Comment by bruno105** [comment]
Its because your ExileCore.dll arent updated, u need the last version of Instanc.sc  ( GetText its a "new" method from instant.sc hud version )

**Comment by Palliridium** [comment]
Thank you for your answer
This means this won't work with Queuete/ExileApi right? is it a private repo or hud? if this is public I'll give it a try! :)
